src/CodeRedCreations/Controllers/PartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CodeRedCreations.Models;
using CodeRedCreations.Data;
using Microsoft.EntityFrameworkCore;
using System.Text;
using System.Text.Encodings.Web;
using CodeRedCreations.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Options;
using CodeRedCreations.Models.Account;
using Newtonsoft.Json;
using Microsoft.Extensions.Caching.Memory;
using CodeRedCreations.Methods;

namespace CodeRedCreations.Controllers
{
    public class PartsController : Controller
    {
        private CodeRedContext _context;
        private readonly AppSettings _settings;
        private readonly IEmailSender _emailSender;
        private readonly UserManager<ApplicationUser> _userManager;
        private IMemoryCache _cache;
        private Common _common;

        public PartsController(
            CodeRedContext context,
            IOptions<AppSettings> settings,
            UserManager<ApplicationUser> userManager,
            IEmailSender emailSender,
            IMemoryCache cache)
        {
            _context = context;
            _settings = settings.Value;
            _userManager = userManager;
            _emailSender = emailSender;
            _cache = cache;
            _common = new Common(cache, context);
        }

        [HttpGet]
        public async Task<IActionResult> Index(string part = "All", string brand = "All", string car = "All", string search = null, int page = 1)
        {
            ViewData["allBrands"] = await _common.GetAllBrandNamesAsync();
            ViewData["allCars"] = await _common.GetAllCarsAsync();
            ViewData["search"] = search;
            ViewData["Page"] = page;
            var products = await GetProductsAsync(part, brand, car, search, page);

            await Task.Run(() =>
            {
                foreach (var product in products.Where(x => x.OnSale == true))
                {
                    if (product.SaleExpiration <= DateTime.UtcNow)
                    {
                        product.OnSale = false;
                        _context.Products.Update(product);
                        _context.SaveChangesAsync();
                    }
                }
            });

            return View(products);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var viewModel = new ProductDetailsView();

            viewModel.ProductModel = await _context.Products.Include(x => x.Images).Include(x => x.Brand).Include(x => x.CarProducts).ThenInclude(x => x.Car).FirstOrDefaultAsync(x => x.PartId == id);
            viewModel.Images = viewModel.ProductModel.Images;

            if (user != null)
            {
                viewModel.UserReferral = await _context.UserReferral.FirstOrDefaultAsync(x => x.UserId == user.Id);
            }

            // Refferal Check
            if (HttpContext.Request.Cookies["Referral"] != null)
            {
                var referralCookie = await Task.Factory.StartNew(() => JsonConvert.DeserializeObject<UserReferral>(HttpContext.Request.Cookies["Referral"]));
                if (referralCookie != null && (user != null && referralCookie.UserId != user.Id) || user == null)
                {
                    viewModel.PromoModel = await _common.GetPromoAsync(referralCookie);
                }
            }

            // Promo
            if (viewModel.PromoModel != null)
            {
                var promoPrice = await ApplyPromoCode(viewModel);

                if (viewModel.ProductModel.Price != promoPrice)
                {
                    viewModel.NewPrice = promoPrice;
                }
            }

            // Store Credit
            if (TempData["StoreCredit"] != null)
            {
                var refAmount = decimal.Parse(TempData["StoreCredit"].ToString());

                viewModel.NewPrice = ((viewModel.ProductModel.Price - refAmount) <= 0 ? 0.01m : (viewModel.ProductModel.Price - refAmount));
            }

            // Sale
            if (viewModel.ProductModel.OnSale)
            {
                if (viewModel.ProductModel.SaleExpiration == null || viewModel.ProductModel.SaleExpiration >= DateTime.UtcNow)
                {
                    if (viewModel.ProductModel.SaleAmount != null)
                    {
                        viewModel.NewPrice = viewModel.ProductModel.Price - (decimal)viewModel.ProductModel.SaleAmount;
                    }
                    else
                    {
                        var discount = viewModel.ProductModel.Price * (decimal)(viewModel.ProductModel.SalePercent / 100m);
                        viewModel.NewPrice = viewModel.ProductModel.Price - discount;
                    }
                }
                else
                {
                    var product = viewModel.ProductModel;
                    product.OnSale = false;

                    _context.Products.Update(product);
                    await _context.SaveChangesAsync();
                }
            }

            return View(viewModel);
        }

        [HttpGet]
#pragma warning disable CS0108 // Member hides inherited member; missing new keyword
        public IActionResult Request()
        {
            return View(new ProductRequestModel());
        }

        [HttpPost]
#pragma warning disable CS0108 // Member hides inherited member; missing new keyword
        public async Task<IActionResult> Request(ProductRequestModel request)
        {
            if (ModelState.IsValid)
            {
                var from = (request.FromEmail != null) ? request.FromEmail : "Anonymous";
                var body = $"<p>New part request from: {from}</p><dl><dt>Brand Name:</dt><dd>{request.Part.Brand.Name}</dd><dt>Part Name:</dt><dd>{request.Part.Name}</dd><dt>Part Type:</dt><dd>{request.Part.PartType}</dd></dl>";
                await _emailSender.SendEmailAsync("Dakota@CodeRedPerformance.com", "Product Request", "Part Request", body);

                TempData["Message"] = "Request sent!";
                return RedirectToAction("Request");
            }

            TempData["Message"] = "Request failed to send.";
            return View(request);

        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BuyNow(ProductDetailsView model, decimal? refAmount)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            model.ProductModel = await _context.Products.Include(x => x.Brand).FirstOrDefaultAsync(x => x.PartId == model.ProductModel.PartId);

            if (model.PromoModel != null)
            {
                model.PromoModel = await _context.Promos.Include(x => x.ApplicableParts).FirstOrDefaultAsync(x => x.Id == model.PromoModel.Id);
                var promo = model.PromoModel;
                var timesUsed = promo.TimesUsed;
                model.ProductModel.Price = await ApplyPromoCode(model);
                timesUsed++;
                await _context.SaveChangesAsync();
            }

            if (user != null)
            {
                var userRef = await _context.UserReferral.FirstOrDefaultAsync(x => x.Id == model.UserReferral.Id && x.UserId == user.Id);
                if (refAmount != null && userRef != null)
                {
                    if (refAmount > userRef.Earnings)
                    {
                        refAmount = userRef.Earnings;
                    }

                    decimal price = ((model.ProductModel.Price - (decimal)refAmount) <= 0 ? 0.01m : (model.ProductModel.Price - (decimal)refAmount));
                    model.ProductModel.Price = Math.Round(price, 2);
                }
            }

            if (model.ProductModel != null)
            {
                var url = (HttpContext.Request.Host.Host.ToUpper().Contains("LOCALHOST")) ?
                    "https://www.sandbox.paypal.com/us/cgi-bin/webscr" : "https://www.paypal.com/us/cgi-bin/webscr";
                var paypalBusiness = _settings.PaypalBusiness;

                var builder = new StringBuilder();
                builder.Append(url);

                builder.Append($"?cmd=_xclick&business={UrlEncoder.Default.Encode(paypalBusiness)}");
                builder.Append($"&lc=US&no_note=0&currency_code=USD&tax_rate=9");
                builder.Append($"&custom={UrlEncoder.Default.Encode(model.ProductModel.PartNumber)}");
                builder.Append($"&item_name={UrlEncoder.Default.Encode($"{model.ProductModel.Brand.Name} - {model.ProductModel.Name}: #{model.ProductModel.PartNumber}")}");
                builder.Append($"&amount={UrlEncoder.Default.Encode(model.ProductModel.SalePrice.ToString())}");
                builder.Append($"&return={UrlEncoder.Default.Encode($"https://{HttpContext.Request.Host.Value}/Home/ThankYou?id={model.ProductModel.PartId}")}");
                builder.Append($"&cancel_return={UrlEncoder.Default.Encode($"https://{HttpContext.Request.Host.Value}/Parts/Details?id={model.ProductModel.PartId}")}");
                builder.Append($"&quantity={UrlEncoder.Default.Encode(model.Quantity.ToString())}");
                builder.Append($"&shipping={UrlEncoder.Default.Encode(Math.Round((decimal)model.Quantity * model.ProductModel.Shipping, 2).ToString())}");
                builder.Append($"&item_number={UrlEncoder.Default.Encode(model.ProductModel.PartNumber)}");

                TempData["ThankYouValidation"] = true;
                TempData["RefAmount"] = refAmount.ToString();
                return Redirect(builder.ToString());
            }

            return RedirectToAction("Details", model.ProductModel.PartId);
        }

        public async Task<IActionResult> PromoCode(ProductDetailsView model)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

src/CodeRedCreations/Views/Admin/AddProduct.cshtml
@model CodeRedCreations.Models.AddNewProductModel
@using System.Linq;

@{
    var query = (Context.Request.Query["section"].FirstOrDefault() == null) ? string.Empty : Context.Request.Query["section"].First().ToString();
    ViewData["Title"] = "Add New Products";
}
<h2>@ViewData["Title"]</h2>
<p class="text-success">@TempData["SuccessMessage"]</p>

<ul class="nav nav-tabs" style="margin-top: 10px;">
    <li id="tabBrand" class="@((query.ToUpper() == "BRAND") ? "active" : "")"><a data-toggle="tab" href="#addBrand">Add Brand</a></li>
    <li id="tabPart" class="@((query.ToUpper() == "PART") ? "active" : "")"><a data-toggle="tab" href="#addPart">Add Part</a></li>
    <li id="tabCar" class="@((query.ToUpper() == "CAR") ? "active" : "")"><a data-toggle="tab" href="#addCar">Add Car</a></li>
</ul>

<div class="tab-content">
    <div id="addBrand" class="tab-pane fade @((query.ToUpper() == "BRAND") ? "in active" : "")">
        <form asp-controller="Admin" asp-action="AddBrand" id="AddBrandForm" method="post" class="form-horizontal">
            <h4>Add a new brand. <span class="small pull-right"><a asp-area="" asp-controller="Admin" asp-action="AddProduct" asp-route-section="BRAND">+ Add New</a></span></h4> 
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Brand.Name" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Brand.Name" class="form-control" />
                    <span asp-validation-for="Brand.Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Brand.Description" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <textarea rows="10" asp-for="Brand.Description" class="form-control"></textarea>
                    <span asp-validation-for="Brand.Description" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-default">Add New Brand</button>
                </div>
            </div>
        </form>
    </div>

    <div id="addPart" class="tab-pane fade @((query.ToUpper() == "PART") ? "in active" : "")">
        <form asp-controller="Admin" asp-action="AddPart" id="AddPartForm" method="post" class="form-horizontal" enctype="multipart/form-data">
            <h4>Add a new part. <span class="small pull-right"><a asp-area="" asp-controller="Admin" asp-action="AddProduct" asp-route-section="PART">+ Add New</a></span></h4> 
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <input asp-for="Part.PartId" hidden="hidden" class="hidden" />
            <div class="form-group">
                <label asp-for="Part.Brand" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <select asp-for="Part.Brand.BrandId" class="form-control selectpicker" data-show-subtext="true" data-live-search="true">
                        @foreach (var brand in Model.Brands)
                        {
                            <option value="@brand.BrandId">@brand.Name</option>
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Part.PartNumber" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Part.PartNumber" class="form-control" />
                    <span asp-validation-for="Part.PartNumber" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Part.Name" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Part.Name" class="form-control" />
                    <span asp-validation-for="Part.Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Part.Description" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <textarea asp-for="Part.Description" class="form-control" spellcheck="true" rows="5"></textarea>
                    <span asp-validation-for="Part.Description" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Part.PartType" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <select asp-for="Part.PartType" asp-items="Html.GetEnumSelectList<CodeRedCreations.Models.PartTypeEnum>()" class="form-control selectpicker" data-show-subtext="true" data-live-search="true"></select>
                    <span asp-validation-for="Part.PartType" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Part.CarProducts" class="col-md-2 control-label"></label>
                <div class="col-md-5">
                    <select id="CompatibleCarIds" name="CompatibleCarIds" multiple class="form-control selectpicker" data-show-subtext="true" data-live-search="true">
                        @foreach (var item in Model.Cars.OrderBy(x => x.Make).ThenBy(x => x.Model))
                        {
                            if (Model.Part.CarProducts != null && Model.Part.CarProducts.FirstOrDefault(x => x.CarId == item.CarId) != null)
                            {
                                <option selected="selected" value="@item.CarId">@item.Make - @item.Model</option>
                            }
                            else
                            {
                                <option value="@item.CarId">@item.Make - @item.Model</option>
                            }
                        }
                    </select>
                    <span asp-validation-for="Part.CarProducts" class="text-danger"></span>
                </div>
                <div class="col-md-5">
                    <input asp-for="Part.Years" class="form-control" placeholder="Car Years" />
                    <span asp-validation-for="Part.Years" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Part.Price" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Part.Price" class="form-control" />
                    <span asp-validation-for="Part.Price" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Part.Shipping" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Part.Shipping" class="form-control" />
                    <span asp-validation-for="Part.Shipping" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label title="Images" class="col-md-2 control-label">Images (@((Model.Part.Images == null) ? 0 : Model.Part.Images.Count()))</label>
                <div class="col-md-10">
                    <input name="Images" type="file" multiple class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-6">
                    <button type="submit" class="btn btn-default">Upsert Product</button>
                </div>
                <div class="col-md-4">
                    @if (Model.Part != null)
                    {
                        <a class="pull-right btn btn-default" asp-controller="Admin" asp-action="NewSimilarProduct" asp-route-id="@Model.Part.PartId">+ New Similar Product</a>
                    }
                </div>
            </div>
        </form>

        <hr />
        <h3>Upload Excel</h3>
        <form asp-controller="Admin" asp-action="AddMultipleProducts"method="post" class="form-horizontal" enctype="multipart/form-data">
            <div class="form-group">
                <label class="col-md-2 control-label">Upload Multiple Products</label>
                <div class="col-md-10">
                    <input name="Excel" type="file" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Product Images</label>
                <div class="col-md-10">
                    <input name="Images" type="file" multiple class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-default">Upload Excel File</button>
                </div>
            </div>
        </form>

    </div>

    <div id="addCar" class="tab-pane fade  @((query.ToUpper() == "CAR") ? "in active" : "")">
        <form asp-controller="Admin" asp-action="AddCar" id="AddCarForm" method="post" class="form-horizontal">
            <h4>Add a new car. <span class="small pull-right"><a asp-area="" asp-controller="Admin" asp-action="AddProduct" asp-route-section="CAR">+ Add New</a></span></h4> 
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <input hidden="hidden" class="hidden" asp-for="NewCar.CarId" />
            <div class="form-group">
                <label asp-for="NewCar.Make" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="NewCar.Make" class="form-control" />
                    <span asp-validation-for="NewCar.Make" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="NewCar.Model" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="NewCar.Model" class="form-control" />
                    <span asp-validation-for="NewCar.Model" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-default">Add New Car</button>
                </div>
            </div>
        </form>
    </div>
</div>

src/CodeRedCreations/Views/Admin/Index.cshtml
@model List<CodeRedCreations.Models.ApplicationUser>
@inject Microsoft.AspNetCore.Identity.UserManager<CodeRedCreations.Models.ApplicationUser> _userManager;
@{
    ViewData["Title"] = "Admin control panel";
}
<h2>@ViewData["Title"]</h2>
<p class="text-success">@ViewData["SuccessMessage"]</p>
<div class="col-md-6">
    <h4>Tools</h4>
    <hr />
        <div class="col-md-6">
            <ul class="list-unstyled">
                <li><a asp-area="" asp-controller="Admin" asp-action="ManageUsers">Manage Users</a></li>
                <li><a asp-area="" asp-controller="Admin" asp-action="ManageBrands">Manage Brands</a></li>
                <li><a asp-area="" asp-controller="Admin" asp-action="ManageCars">Manage Cars</a></li>
                <li><a asp-area="" asp-controller="Admin" asp-action="ManagePromos">Manage Promos</a></li>
                <li><a asp-area="" asp-controller="Admin" asp-action="ManagePayouts">Manage Payouts</a></li>
            </ul>
        </div>
        <div class="col-md-6">

            <ul class="list-unstyled">
                <li><a asp-area="" asp-controller="Admin" asp-action="AddProduct" asp-route-section="PART">+ Add New Product</a></li>
                <li><a asp-area="" asp-controller="Admin" asp-action="AddProduct" asp-route-section="BRAND">+ Add New Brand</a></li>
                <li><a asp-area="" asp-controller="Admin" asp-action="AddProduct" asp-route-section="CAR">+ Add New Car</a></li>
            </ul>
        </div>
</div>
<div class="col-md-6">
    <h4>User List</h4>
    <hr />
    <p>Total Users: @Model.Count()</p>
    <ol style="height: 200px; overflow-y: auto;">
        @foreach (var item in Model)
        {
        <li class="text-capitalize">
            @if (_userManager.GetRolesAsync(await _userManager.FindByEmailAsync(item.Email)).Result.Contains("Admin"))
            {
                <span class="text-red">@item.UserName</span>
            }
            else
            {
                @item.UserName
            }
        </li>
        }
    </ol>
</div>

src/CodeRedCreations/Views/Admin/ManageBrands.cshtml
@model List<CodeRedCreations.Models.BrandModel>
@{
    ViewData["Title"] = "Manage Brands";
}
<div class="row">
    <div class="col-md-12">
        <table class="table table-responsive table-hover table-condensed">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th></th>
                    <th class="text-right"><a asp-controller="Admin" asp-action="AddProduct" asp-route-section="BRAND">+</a></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var brand in Model)
                {
                    <tr>
                        <td>@brand.BrandId</td>
                        <td>
                            <a asp-controller="Admin" asp-action="ManageProducts" asp-route-id="@brand.BrandId">@brand.Name (@brand.Products.Count())</a>
                            <form asp-controller="Admin" asp-action="BrandSale" method="post" class="form-inline">
                                <input name="BrandId" id="BrandId" value="@brand.BrandId" hidden="hidden" class="hidden" />
                                <div class="form-group">
                                    <div class="form-group">
                                        <input type="number" name="SalePercent" id="SalePercent" class="form-control" placeholder="Sale Percent" />
                                    </div>
                                    <div class="form-group">
                                        <input type="number" name="SaleAmount" id="SaleAmount" class="form-control" placeholder="Sale Amount" />
                                    </div>
                                    <div class="form-group">
                                        <input name="SaleExpiration" id="SaleExpiration" class="form-control datepicker" />
                                    </div>
                                    <div class="form-group">
                                        <div class="btn-group">
                                            <button type="submit" class="btn btn-default">Set Sale</button>
                                            <a asp-controller="Admin" asp-action="ClearAllSales" asp-route-id="@brand.BrandId" class="btn btn-default">Clear All Sales</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </td>
                        <td><a asp-controller="Admin" asp-action="AddProduct" asp-route-id="@brand.BrandId" asp-route-section="BRAND">Edit</a></td>
                        <td>
                            @if (brand.Products.Count == 0)
                            {
                                <a asp-controller="Admin" asp-action="DeleteBrand" asp-route-id="@brand.BrandId" onclick="return confirm('Are you sure you want to delete: @brand.Name?');">Delete</a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

src/CodeRedCreations/Views/Admin/ManageProducts.cshtml
@model CodeRedCreations.Models.BrandModel
@using CodeRedCreations.Methods
@{
    ViewData["Title"] = "Manage Products";
}
<h2>@ViewData["Title"]</h2>
<a asp-area="" asp-controller="Admin" asp-action="AddProduct">+ Add New Product</a>
<a class="pull-right" asp-area="" asp-controller="Admin" asp-action="AdjustShipping">Adjust All Shipping</a>
<div class="row">
    <div class="col-md-12">
        <table class="table table-responsive table-hover table-condensed">
            <thead>
                <tr>
                    <th>Id</th>
                    <th colspan="2">Name</th>
                    <th>Price/Shipping</th>
                    <th></th>
                    <th class="text-right"><a asp-controller="Admin" asp-action="AddProduct" asp-route-section="PART">+</a></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var product in Model.Products.OrderBy(x => x.Name))
                {
                    var cars = product.CarProducts.Where(x => x.ProductId == product.PartId).Select(x => x.Car);
                    <tr>
                        <td>@product.PartId</td>
                        <td><img id="@product.PartId" class="img-responsive product-image" src="~/images/Logo-small-text.png" width="100" data-url="@Url.Action("GetProductImageAsync", "Parts")" /></td>
                        <td>
                            @product.Name (@product.PartType)
                            <ul class="small">
                                @foreach (var car in cars)
                                {
                                    <li>
                                        @car.Make @car.Model: @product.Years
                                    </li>
                                }
                            </ul>

                            <form asp-controller="Admin" asp-action="PartSale" method="post" class="form-inline">
                                <input asp-for="@product.PartId" hidden="hidden" class="hidden" />
                                <div class="form-group">
                                    <input type="checkbox" asp-for="@product.OnSale" />
                                </div>
                                <div class="form-group">
                                    <input type="number" asp-for="@product.SalePercent" class="form-control" placeholder="Sale Percent" />
                                </div>
                                <div class="form-group">
                                    <input type="number" asp-for="@product.SaleAmount" class="form-control" placeholder="Sale Amount" />
                                </div>
                                <div class="form-group">
                                    <input asp-for="@product.SaleExpiration" class="form-control datepicker" value="@((product.SaleExpiration.HasValue) ? product.SaleExpiration.Value.ToLocalTime().ToString("MM/dd/yyyy") : "") " />
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-default">Set Sale</button>
                                </div>
                            </form>
                        </td>
                        <td>@product.Price.ToString("C2") <p>+@product.Shipping.ToString("C2") s/h</p></td>
                        <td><a asp-controller="Admin" asp-action="AddProduct" asp-route-id="@product.PartId" asp-route-section="PART">Edit</a></td>
                        <td><a class="pull-right" asp-controller="Admin" asp-action="DeletePart" asp-route-id="@product.PartId" onclick="return confirm('Are you sure you want to delete: @product.Name?');">Delete</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>